AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  iotstreamDatabase:
    Type: AWS::Timestream::Database
  sensoreventsTable:
    Type: AWS::Timestream::Table
    Properties:
      DatabaseName:
        Ref: iotstreamDatabase
  iotTimestreamAppSyncApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: iot-timestream-appsync-api
      AuthenticationType: API_KEY
      XrayEnabled: true
  GraphQLSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId:
        Fn::GetAtt:
        - iotTimestreamAppSyncApi
        - ApiId
      Definition: "schema {\n  query: Query\n}\n\ntype IOT {\n  fleet: String\n  fuel_capacity_in_litres:\
        \ String\n  load_capacity_in_tons: String\n  make: String\n  current_fuel_lvl_in_litres:\
        \ String\n  gps_location_latlong: String\n  model: String\n  truck_id: String\n\
        }\n\ntype Query {\n  getSensorData(durationInMinutes: Int): [IOT]\n}\n"
  ApiKey:
    Type: AWS::AppSync::ApiKey
    DependsOn:
    - GraphQLSchema
    Properties:
      ApiId:
        Fn::GetAtt:
        - iotTimestreamAppSyncApi
        - ApiId
      Description: Public access
  DataSourceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: appsync.amazonaws.com
      Policies:
      - PolicyName: lambdaInvokeFunction
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource:
            - Fn::GetAtt:
              - DataSourceFunction
              - Arn
            - Fn::Sub: ${DataSourceFunction.Arn}:*
  DataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId:
        Fn::GetAtt:
        - iotTimestreamAppSyncApi
        - ApiId
      Type: AWS_LAMBDA
      Name: lambdaDatasource
      LambdaConfig:
        LambdaFunctionArn:
          Fn::GetAtt:
          - DataSourceFunction
          - Arn
      ServiceRoleArn:
        Fn::GetAtt:
        - DataSourceRole
        - Arn
  Resolver:
    Type: AWS::AppSync::Resolver
    DependsOn:
    - GraphQLSchema
    Properties:
      ApiId:
        Fn::GetAtt:
        - iotTimestreamAppSyncApi
        - ApiId
      FieldName: getSensorData
      TypeName: Query
      DataSourceName:
        Fn::GetAtt:
        - DataSource
        - Name
      Kind: UNIT
  DataSourceFunction:
    Type: AWS::Serverless::Function
    Metadata:
      cfn_nag:
        rules_to_suppress:
        - id: W89
          reason: VPC not required.
        - id: W92
          reason: Reserved Concurrency not required.
        - id: W11
          reason: Resource level permissions not available for this API.
    Properties:
      Runtime: nodejs14.x
      MemorySize: 1024
      Timeout: 2
      Handler: index.handler
      Environment:
        Variables:
          TIMESTREAM_DB_NAME:
            Ref: iotstreamDatabase
          TIMESTREAM_TABLE_NAME:
            Fn::GetAtt:
            - sensoreventsTable
            - Name
      Policies:
      - Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - timestream:DescribeEndpoints
          Resource: '*'
        - Effect: Allow
          Action:
          - timestream:Select
          Resource:
            Fn::Sub: arn:${AWS::Partition}:timestream:${AWS::Region}:${AWS::AccountId}:database/${iotstreamDatabase}/table/${sensoreventsTable.Name}
      CodeUri: s3://solution-repo-eu-west-1/80c9462bac01b398b2142889a5a105bc
  ScheduledFunction:
    Type: AWS::Serverless::Function
    Metadata:
      cfn_nag:
        rules_to_suppress:
        - id: W89
          reason: VPC not required.
        - id: W92
          reason: Reserved Concurrency not required.
        - id: W11
          reason: Resource level permissions not available for this API.
    Properties:
      Runtime: python3.9
      MemorySize: 1024
      Timeout: 5
      Handler: lambda_function.lambda_handler
      Environment:
        Variables:
          TIMESTREAM_DB_NAME:
            Ref: iotstreamDatabase
          TIMESTREAM_TABLE_NAME:
            Fn::GetAtt:
            - sensoreventsTable
            - Name
      Policies:
      - Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - timestream:DescribeEndpoints
          Resource: '*'
        - Effect: Allow
          Action:
          - timestream:WriteRecords
          Resource:
            Fn::Sub: arn:${AWS::Partition}:timestream:${AWS::Region}:${AWS::AccountId}:database/${iotstreamDatabase}/table/${sensoreventsTable.Name}
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: rate(2 minutes)
      CodeUri: s3://solution-repo-eu-west-1/4758ae3e162fb7179fd496f34b45ef46
Outputs:
  GraphQLAPIURL:
    Value:
      Fn::GetAtt:
      - iotTimestreamAppSyncApi
      - GraphQLUrl
  GraphQLAPIKey:
    Value:
      Fn::GetAtt:
      - ApiKey
      - ApiKey
  StackRegion:
    Value:
      Ref: AWS::Region
  TimestreamDatabaseARN:
    Value:
      Fn::GetAtt:
      - iotstreamDatabase
      - Arn
  TableARN:
    Value:
      Fn::GetAtt:
      - sensoreventsTable
      - Arn
